version: '2'
services:
    newoapp-app:
        image: newoapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://newoapp-postgresql:5432/NewoApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://newoapp-elasticsearch:9200
        ports:
            - 8080:8080
    newoapp-postgresql:
        extends:
            file: postgresql.yml
            service: newoapp-postgresql
    newoapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: newoapp-elasticsearch
